version: "3.1"

networks:
  default:
  nginx_main:
    external: true

services:

    jenkins:
        build: ./jenkins_container/
        restart: unless-stopped
        networks:
          default:
          nginx_main:
            ipv4_address: 172.16.0.11
        secrets:
          - jenkins-user
          - jenkins-pass
        volumes:
          - ./jenkins_container/var/jenkins_home:/var/jenkins_home

secrets:
  certbot_email:
    file: ./secrets/certbot_email.txt
  jenkins-user:
    file: ./secrets/jenkins-user.txt
  jenkins-pass:
    file: ./secrets/jenkins-pass.txt
