version: "3.1"

networks:
  default:
  nginx_main:
    external: true

services:

    jenkins:
        build: ./jenkins_container/
        restart: unless-stopped
        networks:
          default:
          nginx_main:
            ipv4_address: 172.16.0.11
        secrets:
          - jenkins-user
          - jenkins-pass
          - source: jenkins-key
            uid: '1000'
            gid: '1000'
          - source: jenkins-key.pub
            uid: '1000'
            gid: '1000'
        volumes:
          - jenkins_home:/var/jenkins_home

secrets:
  certbot_email:
    file: ./secrets/certbot_email.txt
  jenkins-user:
    file: ./secrets/jenkins-user.txt
  jenkins-pass:
    file: ./secrets/jenkins-pass.txt
  jenkins-key:
    file: ./secrets/jenkins-key
  jenkins-key.pub:
    file: ./secrets/jenkins-key.pub

volumes:
  jenkins_home: